/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as CourseAiRouteImport } from './routes/course.ai'
import { Route as ApiPublicCheckSubscriptionRouteImport } from './routes/api/public/check-subscription'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicTelegramTicketRouteImport } from './routes/api/public/telegram-ticket'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseAiRoute = CourseAiRouteImport.update({
  id: '/course/ai',
  path: '/course/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckSubscriptionRoute =
  ApiPublicCheckSubscriptionRouteImport.update({
    id: '/api/public/check-subscription',
    path: '/api/public/check-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramTicketRoute = ApiPublicTelegramTicketRouteImport.update({
  id: '/api/public/telegram-ticket',
  path: '/api/public/telegram-ticket',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/course/ai': typeof CourseAiRoute
  '/api/public/check-subscription': typeof ApiPublicCheckSubscriptionRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram-ticket': typeof ApiPublicTelegramTicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/course/ai': typeof CourseAiRoute
  '/api/public/check-subscription': typeof ApiPublicCheckSubscriptionRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram-ticket': typeof ApiPublicTelegramTicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/course/ai': typeof CourseAiRoute
  '/api/public/check-subscription': typeof ApiPublicCheckSubscriptionRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram-ticket': typeof ApiPublicTelegramTicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/login'
    | '/offers'
    | '/profile'
    | '/reset-password'
    | '/support'
    | '/upgrade'
    | '/welcome'
    | '/admin/emails'
    | '/course/ai'
    | '/api/public/check-subscription'
    | '/api/public/stripe-webhook'
    | '/api/public/telegram-ticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/login'
    | '/offers'
    | '/profile'
    | '/reset-password'
    | '/support'
    | '/upgrade'
    | '/welcome'
    | '/admin/emails'
    | '/course/ai'
    | '/api/public/check-subscription'
    | '/api/public/stripe-webhook'
    | '/api/public/telegram-ticket'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/login'
    | '/offers'
    | '/profile'
    | '/reset-password'
    | '/support'
    | '/upgrade'
    | '/welcome'
    | '/admin/emails'
    | '/course/ai'
    | '/api/public/check-subscription'
    | '/api/public/stripe-webhook'
    | '/api/public/telegram-ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  UpgradeRoute: typeof UpgradeRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  CourseAiRoute: typeof CourseAiRoute
  ApiPublicCheckSubscriptionRoute: typeof ApiPublicCheckSubscriptionRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicTelegramTicketRoute: typeof ApiPublicTelegramTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/ai': {
      id: '/course/ai'
      path: '/course/ai'
      fullPath: '/course/ai'
      preLoaderRoute: typeof CourseAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-subscription': {
      id: '/api/public/check-subscription'
      path: '/api/public/check-subscription'
      fullPath: '/api/public/check-subscription'
      preLoaderRoute: typeof ApiPublicCheckSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-ticket': {
      id: '/api/public/telegram-ticket'
      path: '/api/public/telegram-ticket'
      fullPath: '/api/public/telegram-ticket'
      preLoaderRoute: typeof ApiPublicTelegramTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  UpgradeRoute: UpgradeRoute,
  WelcomeRoute: WelcomeRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  CourseAiRoute: CourseAiRoute,
  ApiPublicCheckSubscriptionRoute: ApiPublicCheckSubscriptionRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicTelegramTicketRoute: ApiPublicTelegramTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
